# Generated by Django 5.0.6 on 2024-09-11 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('reviews_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('project_img', models.ImageField(default='/pro/pro.jpg', upload_to='')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created'],
            },
        ),
    ]
